### ISSUE TITLE
Report Button

### ISSUE THREAD

**Issue by Phlosioneer** [bykof/what-to-code#1]
Whenever people can post publicly, some people will abuse it. Currently the 2nd most popular idea right now is "Incest Porn Machine Learning."

We need a way to flag ideas as inappropriate or off-topic (e.g. a joke not an idea). Another example is the currently most popular idea, a DDOS attack.

**Comment by chaarlie130** [comment]
I 2nd this idea, currently someone is spamming "Watch Mr. Robot" which makes the recent tab unusable and the random idea button unusable.

**Comment by xyzpw** [comment]
> I 2nd this idea, currently someone is spamming "Watch Mr. Robot" which makes the recent tab unusable and the random idea button unusable.

lol I wonder who did that :D

**Comment by bykof** [comment]
What to code has now recaptchav3 support! So i can close this ticket :)
Also banned words are not allowed
