### ISSUE TITLE
Highlight liked ideas

### ISSUE THREAD

**Issue by kitaboon** [bykof/what-to-code#2]
Hello,
Your site is just amazing, it was exactly what I was researching for weeks xD.
But there one thing not really convenient :
You can't know which ideas you liked (until you click to see if its decrease or increase).
It would be great to highlight liked ideas, with another color or what else.

**Comment by niklasschloegel** [comment]
#9 should add this feature, if accepted.

**Comment by bykof** [comment]
Was done by @niklasschloegel, thank you for that!
