### ISSUE TITLE
antispam

### ISSUE THREAD

**Issue by intexception** [bykof/what-to-code#23]
the website is getting spammed, and some idea has got negative likes... 
![image](https://user-images.githubusercontent.com/80127180/165158495-456e336a-fd43-4e81-aa28-d5879fc71109.png)

**Comment by phant0m2290** [comment]
got this one now. all the same except the number. seen at least like 50 now
![Schermafbeelding 2022-07-18 083445](https://user-images.githubusercontent.com/76474615/179456222-b4e0cea4-416d-41fc-9077-4c120f5a61e8.png)

**Comment by bykof** [comment]
What to code has now recaptchav3 support! So i can close this ticket :)
Also banned words are not allowed
